services:
  zentile:
    build:
      context: .
      target: runner
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CONVEX_SELF_HOSTED_URL=${CONVEX_SELF_HOSTED_URL:-http://convex-backend:3210}
    depends_on:
      convex-backend:
        condition: service_healthy
      init-db:
        condition: service_completed_successfully
      admin-key-generator:
        condition: service_completed_successfully
    command: >
      sh -c '
        # Wait for the admin key to become available
        while [ ! -f /shared/admin_key ]; do
          echo "Waiting for admin key...";
          sleep 2;
        done;
        
        # Export the admin key for Convex CLI
        export CONVEX_SELF_HOSTED_ADMIN_KEY=$(cat /shared/admin_key);
        
        # Run Convex deployment
        npx convex deploy --prod;
        
        # Start the Nuxt application
        node .output/server/index.mjs;
      '
    volumes:
      - admin_keys:/shared:ro # Mount admin key for deployment
    networks:
      - zentile-network

  # Convex Backend Service
  convex-backend:
    image: ghcr.io/get-convex/convex-backend:c1a7ac393888d743e704de56cf569a154b4526d4
    restart: unless-stopped
    stop_grace_period: 10s
    stop_signal: SIGINT
    volumes:
      - convex_data:/convex/data
      - admin_keys:/shared # Also needs access to the key
    ports:
      - "3210:3210"
    environment:
      - INSTANCE_NAME=convex
      - DISABLE_BEACON=${DISABLE_BEACON:-true}
      - POSTGRES_URL=postgres://convex:convex@postgres:5432
      - DO_NOT_REQUIRE_SSL=${DO_NOT_REQUIRE_SSL:-true}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3210/version"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    networks:
      - zentile-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    depends_on:
      postgres:
        condition: service_healthy
      init-db:
        condition: service_completed_successfully

  # Postgres Database Service
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: convex
      POSTGRES_USER: convex
      POSTGRES_PASSWORD: convex
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U convex"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - zentile-network

  # Database Initialization Service
  init-db:
    image: postgres:15-alpine
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGPASSWORD: convex
    entrypoint:
      - sh
      - -c
      - |
        sleep 5
        db_exists=$$(psql -h postgres -U convex -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='convex'")
        if [ "$$db_exists" != "1" ]; then
          psql -h postgres -U convex -d postgres -c "CREATE DATABASE convex"
        else
          echo "Database 'convex' already exists"
        fi
    restart: "no"
    networks:
      - zentile-network

  convex-dashboard:
    image: ghcr.io/get-convex/convex-dashboard:latest
    stop_grace_period: 10s
    stop_signal: SIGINT
    ports:
      - "${DASHBOARD_PORT:-6791}:6791"
    environment:
      - NEXT_PUBLIC_DEPLOYMENT_URL=${NEXT_PUBLIC_DEPLOYMENT_URL:-http://127.0.0.1:3210}
    depends_on:
      convex-backend:
        condition: service_healthy
    networks:
      - zentile-network

  admin-key-generator:
    image: alpine:latest
    volumes:
      - admin_keys:/shared
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: >
      sh -c "
      if [ ! -f /shared/admin_key ]; then
        echo 'Waiting for Convex backend to be ready...'
        # Wait for backend to be accessible
        while ! wget -q --spider http://convex-backend:3210/version; do
          echo 'Backend not ready, waiting...'
          sleep 2
        done
        echo 'Backend is ready, generating admin key...'
        
        # Install docker CLI and curl
        apk add --no-cache docker-cli curl jq
        
        # Try to generate admin key using docker exec on the backend service
        ADMIN_KEY=$$(docker exec zentile-convex-backend-1 ./generate_admin_key.sh 2>/dev/null | tail -1)
        
        if [ -n \"$$ADMIN_KEY\" ] && [ \"$$ADMIN_KEY\" != \"\" ] && [ \"$$ADMIN_KEY\" != \"null\" ]; then
          echo \"$$ADMIN_KEY\" > /shared/admin_key
          echo 'Admin key generated using backend script and saved to /shared/admin_key'
          echo 'Admin key: '$$ADMIN_KEY
        else
          echo 'Failed to generate admin key using backend script, trying API...'
          # Try the API approach as fallback
          ADMIN_KEY=$$(curl -s -X POST http://convex-backend:3210/api/admin_key 2>/dev/null | jq -r '.admin_key' 2>/dev/null)
          
          if [ -n \"$$ADMIN_KEY\" ] && [ \"$$ADMIN_KEY\" != \"null\" ] && [ \"$$ADMIN_KEY\" != \"\" ]; then
            echo \"$$ADMIN_KEY\" > /shared/admin_key
            echo 'Admin key generated via API and saved to /shared/admin_key'
            echo 'Admin key: '$$ADMIN_KEY
          else
            echo 'Both methods failed'
          fi
        fi
      else
        echo 'Admin key already exists, using existing key:'
        cat /shared/admin_key
      fi
      "
    restart: "no"
    depends_on:
      convex-backend:
        condition: service_healthy
    networks:
      - zentile-network

volumes:
  zentile_node_modules:
  zentile_nuxt:
  zentile_output:
  admin_keys:
  postgres_data:
  convex_data:
  convexdev_build_cache:
  zentile_build_cache:

networks:
  zentile-network:
    driver: bridge